// services/excel/fieldMappings.ts
// Defines constants for mapping Excel header variations to standardized field names.

// Base mappings shared across document types
export const BASE_MAPPINGS: Record<string, string> = {
  // Essential IDs
  'LOAD NO': 'loadNumber',
  'Load No': 'loadNumber',
  'LOAD NUMBER': 'loadNumber',
  'Load Number': 'loadNumber',
  'load no': 'loadNumber',
  'load number': 'loadNumber',
  'Order Number': 'orderNumber',
  'ORDER NUMBER': 'orderNumber',
  'Order No': 'orderNumber',
  'ORDER NO': 'orderNumber',
  'Customer PO Number': 'poNumber',
  'CUSTOMER PO NUMBER': 'poNumber',
  'PO Number': 'poNumber',
  'PO NUMBER': 'poNumber',
  'PO No': 'poNumber',
  'PO NO': 'poNumber',
  // Dates
  'Promised Ship Date': 'promisedShipDate',
  'PROMISED SHIP DATE': 'promisedShipDate',
  'Promise Date': 'promisedShipDate',
  'PROMISE DATE': 'promisedShipDate',
  'Ship Date': 'promisedShipDate',
  'SHIP DATE': 'promisedShipDate',
  'Request Date': 'requestDate',
  'REQUEST DATE': 'requestDate',
  'Requested Date': 'requestDate',
  'REQUESTED DATE': 'requestDate',
  // Ship To Info (Raw Fields - Resolver processes these)
  'Address Line 1 and 2': 'shipToAddress',
  'ADDRESS LINE 1 AND 2': 'shipToAddress',
  'Address': 'shipToAddress',
  'ADDRESS': 'shipToAddress',
  'Ship To Address': 'shipToAddress',
  'SHIP TO ADDRESS': 'shipToAddress',
  'DELIVERY ADDRESS': 'shipToAddress',
  'Delivery Address': 'shipToAddress',
  // Variations for Ship To State
  'State/ Province': 'shipToState',
  'STATE/ PROVINCE': 'shipToState',
  'State / Province': 'shipToState',
  'STATE / PROVINCE': 'shipToState',
  'State': 'shipToState',
  'STATE': 'shipToState',
  'Province': 'shipToState',
  'PROVINCE': 'shipToState',
  'shipToState': 'shipToState',
  'shiptostate': 'shipToState',
  'shptostate': 'shipToState',
  'ship to state': 'shipToState',
  // 'City': 'shipToCity', // Add if City is a separate column
  // 'Postal Code': 'shipToPostalCode', // Add if Postal Code is separate
  'Ship To Customer Name': 'shipToCustomer',
  'SHIP TO CUSTOMER NAME': 'shipToCustomer',
  'Ship To Customer': 'shipToCustomer',
  'SHIP TO CUSTOMER': 'shipToCustomer',
  'Customer Name': 'shipToCustomer',
  'CUSTOMER NAME': 'shipToCustomer',
  'Customer': 'shipToCustomer',
  'CUSTOMER': 'shipToCustomer',
  // Contact
  'CONTACT NO': 'contactNumber',
  'Contact No': 'contactNumber',
  'Contact Number': 'contactNumber',
  'CONTACT NUMBER': 'contactNumber',
  'Phone': 'contactNumber',
  'PHONE': 'contactNumber',
  // Remarks
  'REMARK': 'remarks',
  'Remark': 'remarks',
  'Remarks': 'remarks',
  'REMARKS': 'remarks',
  'Notes': 'remarks',
  'NOTES': 'remarks',
  'Note': 'remarks',
  'NOTE': 'remarks',
  'Comment': 'remarks',
  'COMMENT': 'remarks',
  'Comments': 'remarks',
  'COMMENTS': 'remarks',
  // Item fields
  '2nd Item Number': 'secondaryItemNumber',
  'Secondary Item Number': 'secondaryItemNumber',
  'Item Number': 'itemNumber',
  'ITEM NUMBER': 'itemNumber',
  'Item No': 'itemNumber',
  'ITEM NO': 'itemNumber',
  'Item': 'itemNumber',
  'ITEM': 'itemNumber',
  'Description 1': 'description',
  'DESCRIPTION 1': 'description',
  'Description': 'description',
  'DESCRIPTION': 'description',
  'Item Description': 'description',
  'ITEM DESCRIPTION': 'description',
  'Lot Serial Number': 'lotSerialNumber',
  'LOT SERIAL NUMBER': 'lotSerialNumber',
  'Lot Number': 'lotSerialNumber',
  'LOT NUMBER': 'lotSerialNumber',
  'Serial Number': 'lotSerialNumber',
  'SERIAL NUMBER': 'lotSerialNumber',
  'Serial No': 'lotSerialNumber',
  'SERIAL NO': 'lotSerialNumber',
  'Lot No': 'lotSerialNumber',
  'LOT NO': 'lotSerialNumber',
  'Quantity Ordered': 'quantity',
  'QUANTITY ORDERED': 'quantity',
  'Quantity': 'quantity',
  'QUANTITY': 'quantity',
  'Qty': 'quantity',
  'QTY': 'quantity',
  'UOM': 'uom',
  'Unit of Measure': 'uom',
  'UNIT OF MEASURE': 'uom',
  'Unit': 'uom',
  'UNIT': 'uom',
  'Weight (KG)': 'weight',
  'WEIGHT (KG)': 'weight',
  'Weight': 'weight',
  'WEIGHT': 'weight',
  'Weight (kg)': 'weight',
  'WEIGHT (kg)': 'weight',
  // Fields from old parser added here
  'Actual Delivery Date': 'actualDeliveryDate',
  'ACTUAL DELIVERY DATE': 'actualDeliveryDate',
  'Delivered Date': 'actualDeliveryDate',
  'DELIVERED DATE': 'actualDeliveryDate',
  'Order type': 'orderType',
  'ORDER TYPE': 'orderType',
  'Type': 'orderType',
  'TYPE': 'orderType',
  'Bin': 'bin',
  'BIN': 'bin',
  // Financial/Rate Fields (Mapped to database schema fields)
  'Trip Rates': 'tripRate',
  'TRIP RATES': 'tripRate',
  'Drop': 'dropCharge',
  'DROP': 'dropCharge',
  'Manpower': 'manpowerCharge',
  'MANPOWER': 'manpowerCharge',
  'Total': 'totalCharge',
  'TOTAL': 'totalCharge',
  // ADDED Mappings for Truck Details
  'TRUCK DETAILS': 'truckDetails',
  'Truck Details': 'truckDetails',
  'truck details': 'truckDetails',
  'misc_truck_details': 'truckDetails',
};

// Specific mappings for pickup/origin location (Raw Input)
export const PICKUP_MAPPINGS: Record<string, string> = {
  'Pick up warehouse': 'pickupWarehouse',
  'Pickup Warehouse': 'pickupWarehouse',
  'PICKUP WAREHOUSE': 'pickupWarehouse',
  'Pickup Location': 'pickupWarehouse',
  'PICKUP LOCATION': 'pickupWarehouse',
  'Origin Warehouse': 'pickupWarehouse',
  'ORIGIN WAREHOUSE': 'pickupWarehouse',
  'Origin Location': 'pickupWarehouse',
  'ORIGIN LOCATION': 'pickupWarehouse',
  'Transporter': 'pickupWarehouse',
  'TRANSPORTER': 'pickupWarehouse',
};

// Mapping for ship-to area (Raw Input)
export const AREA_MAPPINGS: Record<string, string> = {
  'Ship To Area': 'shipToArea',
  'SHIP TO AREA': 'shipToArea',
  'Area': 'shipToArea',
  'AREA': 'shipToArea',
}; 